services:
  stev_btipay.factory:
    class: Stev\BTIPayBundle\Services\BTIPayFactory
    arguments: ['%stev_bti_pay.username%','%stev_bti_pay.password%', '%stev_bti_pay.isTest%']
  stev_btipay.client:
    class: Stev\BTIPay
    factory: 'stev_btipay.factory:initClient'